version: 2
jobs:
  build:
    working_directory: ~/
    docker:
      - image: node:8.9.4

    steps:
      - checkout
      - restore_cache:
          key: circleCI-playground-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test
          command: npm run test:ci
      - save_cache:
          key: circleCI-playground-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/node_modules